package exerciseproblem.ch5.No8;

import java.util.Scanner;

/*
이 문제를 풀려면 java.util.Scanner 클래스의 소스 코드를 읽어야 한다. Scanner를 사용할 때 입력이 잘못되면 Scanner 클래스는 해당 예외를 잡아내고 입력
소스에서 읽기를 중단한다. 스캐너가 닫힐 때 무슨 일이 일어날까? 그리고 입력 소스를 닫는 도중에 예외가 일어날까? 이 동작을 try-with-resources문에서 억제된
예외를 다루는 방법과 비교하라.
 */
public class Main {

}
